load("@rules_cc//cc:defs.bzl", "cc_binary")


cc_binary(
    name = "profiling",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "//:inversify",
    ],
    visibility = ["//visibility:public"]
)
